### ISSUE TITLE
Issues & Contributions

### ISSUE THREAD

**Issue by MuhaddiMu** [MuhaddiMu/Idea-ReVue#5]
Idea ReVue is Open Source. It is live up and running 🙌

We have a general ToDo list updated on README.

Facing any Issues or weird behaviour (yes, apps behave)? Feel free to open a [new issue](https://github.com/MuhaddiMu/Idea-ReVue/issues/new) and I will ideate on it where I went wrong.

### Todos 📋
 - [x] Authentication
 - [x] Display My Ideas
 - [x] Display Public Ideas
 - [x] Love Count
 - [x] Update Account
 - [x] Edit, Delete Personal Ideas
 - [ ] Idea Search
 - [ ] Single Idea Sharable Link
 - [ ] Idea Collaboration
 - [ ] Reactive Page Title
 - [ ] Idea Love Count
 - [ ] Idea board comments
 - [ ] Idea Board Prioritization
 - [ ] Customize Dashboard
 - [ ] Server Side Rendering with Nuxt.Js
 - [ ] Mailingbehave
 - [ ] Notifications
 - [ ] PWA Support

 1. Make all changes to the `develop` branch.
 2. Update this Issue and README if necessary.
 3. Submit a Pull Request and make sure to reference the issue.
